# Stage 1: Build dell'app Angular
FROM node:20 AS build

WORKDIR /src/app

# Copia i file necessari per l'installazione delle dipendenze
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia tutto il resto del codice dell'applicazione
COPY . .

# Build dell'app Angular in modalità produzione
RUN npm run build --prod

# Stage 2: Serve l'app con Nginx
FROM nginx:alpine

# Copia il risultato della build dall'immagine precedente
COPY --from=build src/app/dist /usr/share/nginx/html

# Esponi la porta 80 su cui Nginx sta girando
EXPOSE 4020

# Comando per avviare Nginx
CMD ["nginx", "-g", "daemon off;"]
