# Usa un'immagine base per Node.js
FROM node:16-alpine AS build

# Imposta la directory di lavoro nel container
WORKDIR /app

# Copia il file package.json e package-lock.json
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice dell'app
COPY . .

# Costruisci l'app Angular
RUN npm run build --prod

# Usa un'immagine Nginx per servire l'app
FROM nginx:alpine

# Copia i file costruiti da Angular nella directory di Nginx
COPY --from=build /app/dist/<ecommerce> /usr/share/nginx/html

# Esponi la porta su cui Nginx sta girando
EXPOSE 80

# Comando per eseguire Nginx
CMD ["nginx", "-g", "daemon off;"]
