version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: valedb
      POSTGRES_DB: ecommerce
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build: ./backend
    depends_on:
      db:
        condition: service_healthy
    environment:
     - DOCKERIZED=true
    ports:
      - "5000:5000"  # Esponi la porta 5000 del container
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:
  backend-network:
    driver: bridge