version: '3.8'

services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: valedb
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    networks:
      - backend-network

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:valedb@host.docker.internal:5432/ecommerce
    ports:
      - "5000:5000"
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

networks:
  backend-network:
    driver: bridge