# Usa un'immagine base per Python
FROM python:3.10-slim

# Imposta la directory di lavoro nel container
WORKDIR /app

# Copia il file dei requisiti
COPY requirements.txt .

# Installa le dipendenze
RUN pip install --no-cache-dir -r requirements.txt

# Copia il resto del codice dell'app
COPY . .

# Copia il wait-for-it script
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh


# Esponi la porta su cui Flask sta girando
EXPOSE 5000

# Comando per eseguire l'app
CMD ["/wait-for-it.sh", "db:5432", "--", "python", "server.py"]
